name: CI

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v*'
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements_dev.txt

      - name: Flake8 lint
        uses: TrueBrain/actions-flake8@v2
        with:
          path: custom_components

      - name: Flake8 lint tests
        uses: TrueBrain/actions-flake8@v2
        with:
          path: tests

      - name: Verify import sorting
        run: isort --diff --check-only tests custom_components

  tests:
    name: Run tests (${{ matrix.ha-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ha-version: '2023.3'
            python-version: '3.10'
          - ha-version: '2023.4'
            python-version: '3.10'
          - ha-version: '2023.5'
            python-version: '3.10'
          - ha-version: '2023.6'
            python-version: '3.10'
          - ha-version: '2023.7'
            python-version: '3.10'
          - ha-version: '2023.8'
            python-version: '3.11'
          - ha-version: '2023.9'
            python-version: '3.11'
          - ha-version: '2023.10'
            python-version: '3.11'
          - ha-version: '2023.11'
            python-version: '3.11'
          - ha-version: '2023.12'
            python-version: '3.11'
          - ha-version: '2024.1'
            python-version: '3.11'
          - ha-version: '2024.2'
            python-version: '3.12'
          - ha-version: '2024.4'
            python-version: '3.12'
          - ha-version: '2024.5'
            python-version: '3.12'
            latest: true
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: tests/requirements_${{ matrix.ha-version }}.txt

      - name: Install dependencies
        run: |
          pip install -r tests/requirements_${{ matrix.ha-version }}.txt 

      - name: Test with pytest
        run: |
          pytest \
            -qq \
            --timeout 9 \
            --durations 10 \
            -n auto \
            --cov custom_components.yandex_smart_home \
            --cov-report xml \
            -o console_output_style=count \
            -p no:sugar \
            tests

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        if: ${{ matrix.latest == true }}

  validate:
    name: Validate for HACS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
